
# Copy this to .settings.yaml and fill it out.

# Screeps account info
screeps_username:
screeps_password:
screeps_ptr: false

# Your Account SID from www.twilio.com/console
twilio_sid:

# Your Auth Token from www.twilio.com/console
twilio_token:

# Consider using your number as the sender and receiver
sms_from: '+15555555555'
sms_to: '+15555555555'
